### ISSUE TITLE
Not open source?

### ISSUE THREAD

**Issue by cdnsteve** [nytlabs/github-s3-deploy#5]
Hi there, 

It seems this project isn't open source. There's currently no license file and within the index.js file there is this:
```
Copyright: The New York Times Company
```

Can you please advise?

Thanks,
Steve

**Comment by mboggie** [comment]
I am no longer with The Times, but this was meant to be an Apache-licensed open source project. I've asked a contact there to adjust the LICENSE accordingly, after which point I'll be accepting changes / pull requests. This will ensure that any contributions fall under the same open source license.

Apologies for the oversight.

**Comment by aureq** [comment]
@mboggie Have you had any news on this ?

**Comment by leewardbound** [comment]
updates on this please? i have made modifications to fix #8  and am ready to submit a PR, this is a pretty big buzzkill

**Comment by fabceolin** [comment]
Please update the license.

**Comment by mboggie** [comment]
Apache 2 License has been added; apologies for the delay. I no longer work for The Times and had to get permission to update the repository (since it wasn't yet open source and I was no longer an employee, I was in the same boat as you.) Should be all set!

**Comment by aureq** [comment]
@mboggie Thank you very much for chasing up on this issue. And much appreciated you took the time to reply to everybody here.

@nytlabs that you for releasing this software to the open-source community.
