### ISSUE TITLE
Files are sometimes not modified

### ISSUE THREAD

**Issue by PeterBengtson** [nytlabs/github-s3-deploy#7]
Sometimes, when uploading a new version of a file, a newly changed file will _not_ be uploaded properly. No error codes are issued when this happens, so you can never be quite sure that your work "takes". This is probably due to some async timing issue and should be easy to fix, because as the code stands now, it can't be trusted.

**Comment by keyan** [comment]
@PeterBengtson could you provide any more details about this? Do you have access logs you could share? Something that would help debug this would be great.

**Comment by PeterBengtson** [comment]
The access log entries show nothing untoward: they all report success. I can provide you with an extract if you wish, but there's really nothing in the logs that sheds any light on this. Please let me know.

**Comment by PeterBengtson** [comment]
![screen shot 2017-08-23 at 11 04 56](https://user-images.githubusercontent.com/3897/29608053-596cf300-87f3-11e7-9496-d988d80e0818.PNG)

**Comment by PeterBengtson** [comment]
I found the issue – it had to do with initialization issues and container life and should not occur in your original code. I'm closing this issue.
